[font]
size = 12.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
opacity = 0.6
blur = true
padding = {x=16, y=16}

[colors.primary]
background = "#404040"

[colors.normal]
black   = '#333333'
red     = '#FFB7A8'
green   = '#B9FFA8'
yellow  = '#FFF2D1'
blue    = '#D1D6FF'
magenta = '#FFD1EA'
cyan    = '#D1FFF9'
white   = '#DEDEDE'